### ISSUE TITLE
Expose management API port

### ISSUE THREAD

**Issue by lenkan** [nijel/rabbitmq-action#1]
I am writing tests that are performing some assertions against the management api https://www.rabbitmq.com/management.html#http-api , so it would be convenient to expose 15672 as well.

If you agree I can create a PR. Otherwise, feel free to close.

**Comment by nijel** [comment]
It might be better to use services instead of this action now.

This is what I do:

https://github.com/WeblateOrg/fedora_messaging/blob/66c0399115b6409d7040dd523e870e99c17428e2/.github/workflows/test.yml#L28-L31

**Comment by lenkan** [comment]
Oh, thanks. That seems like the way to go. I'll close this.
